version: '3'
services: 
    hexo_blog:
        build: './dockerfiles/Dockerfile.blog'
    nginx:
        image: nginx:latest
        container_name: nginx
        # build: ./dockerfiles/Dockerfile.nginx
        restart: 'always'
        ports: 
            - '80:80'
            - '443:443'
        volumes: 
            #这里的/www/hexo_ash/pubilc是主机的目录
            #意思是把这个目录挂载到容器的/usr/share/nginx/html目录中
            #该目录防止了网页的静态文件
            - '/www/hexo_ash/pubilc:/usr/share/nginx/html'
            #同理，配置文件
            - '/www/hexo_ash/dockerfiles/conf:/etc/nginx/nginx.conf'
